name: eventmgr

services:
    keycloak:
        container_name: Keycloak_Container
        image: quay.io/keycloak/keycloak:24.0.3
        ports:
            - 8081:8080
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: mariadb
            KC_DB_URL: jdbc:mariadb://host.docker.internal:3306/keycloak?allowMultiQueries=true&createDatabaseIfNotExist=true
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: keycloak
        volumes:
            - ./import:/opt/keycloak/data/import
        command: start-dev --import-realm